project:
  version: @app.version@
  java: @java.version@
  kotlin: @kotlin.version@
  build:
    time: @build.time@
spring:
  profiles:
    active: @profile.active@
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: "/api/v1"
  port: 8081
logging:
  file:
    path: "./logs"