spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/fy_carbon
    username: "fy_carbon"
    password: "nYMKPd4scpyyQZxf"
  mail:
    default-encoding: utf-8
    host: smtp.qiye.aliyun.com
    username: noreplay@x-lf.cn
    password: "X+7ily20040722"
  data:
    redis:
      port: 6379
      host: redis
      database: 0
      password: "jhkdjhkjdhsIUTYURTU_rBpjHG"
logging:
  level:
    root: error
    com.frontleaves.greenchaincarbonledger: debug
    com.frontleaves.greenchaincarbonledger.mappers: info