spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306
    username: "fy_carbon"
    password: "123456"
  mail:
    default-encoding: utf-8
    host: smtp.qiye.aliyun.com
    username: noreplay@x-lf.cn
    password: "X+7ily20040722"
  data:
    redis:
      port: 6379
      host: localhost
      database: 0
      password:
server:
  servlet:
    context-path: "/api/v1"
logging:
  file:
    path: "./logs"
  level:
    root: error
    com.frontleaves.greenchaincarbonledger: debug
    com.frontleaves.greenchaincarbonledger.mappers: info
mybatis:
  configuration:
    map-underscore-to-camel-case: true