project:
  version: 1.0.0-SNAPSHOT
  java: 17.0.9
  kotlin: 1.9.22
  build:
    time: 2024-03-04 14:08:31
spring:
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    context-path: "/api/v1"
  port: 8081
logging:
  file:
    path: "./logs"